//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaySeoul_Session4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Amenity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Amenity()
        {
            this.ItemAmenities = new HashSet<ItemAmenity>();
        }
    
        public long ID { get; set; }
        public System.Guid GUID { get; set; }
        public string Name { get; set; }
        public string IconName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemAmenity> ItemAmenities { get; set; }
    }
}
